[package]
name = "vector-coverage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
gen-iter = "0.2.1"
glm = "0.2.3"
minifb = "0.23.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"

[lib]
name = "svg"
